# Generated by Django 5.0.4 on 2026-01-19 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='frames/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('matched_case_id', models.CharField(blank=True, help_text='ID of matched missing person case if detection occurred', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Frame',
                'verbose_name_plural': 'Frames',
                'db_table': 'frames',
                'ordering': ['-timestamp'],
            },
        ),
    ]
