# Generated by Django 5.0.4 on 2026-01-19 03:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingPerson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Additional details about the missing person')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Missing Person',
                'verbose_name_plural': 'Missing Persons',
                'db_table': 'missing_persons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MissingPersonImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='missing_person_images/')),
                ('embedding_reference', models.CharField(blank=True, help_text='Reference to stored embedding (e.g., file path or ID)', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('missing_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cases.missingperson')),
            ],
            options={
                'verbose_name': 'Missing Person Image',
                'verbose_name_plural': 'Missing Person Images',
                'db_table': 'missing_person_images',
                'ordering': ['-created_at'],
            },
        ),
    ]
